[book]
title = "SQL from Zero to Hero"
description = "Mastering Postgres from First Query to Terabyte Scale"
authors = ["Andy W. Pearson"]
language = "en"
src = ".book-src"

[build]
build-dir = ".book-out"

[output.html]
default-theme = "rust"
preferred-dark-theme = "ayu"
additional-css = ["theme/print.css", "theme/page-turn.css"]
additional-js  = ["theme/page-turn.js"]
smart-punctuation = true

[output.html.print]
enable = true

[output.html.fold]
enable = true
level = 1
